export const RUNTIME_FAILURE_CODES_V4 = [
  'INVALID_CONTRACT',
  'REPOSITORY_NOT_ALLOWED',
  'REPOSITORY_BUSY',
  'BROKER_STATE_CORRUPT',
  'BASE_SHA_INVALID',
  'WORKTREE_CREATION_FAILED',
  'CAPABILITY_UNVERIFIED',
  'SOURCE_SENSITIVITY_UNSUPPORTED',
  'PROCESS_SANDBOX_UNAVAILABLE',
  'REVIEW_SANDBOX_UNAVAILABLE',
  'AUTHENTICATION_FAILED',
  'PROVIDER_UNAVAILABLE',
  'EXECUTOR_INVALID_OUTPUT',
  'EXECUTOR_POLICY_VIOLATION',
  'OUT_OF_SCOPE_CHANGE',
  'VALIDATION_FAILED',
  'REVIEW_REJECTED',
  'REVIEW_ATTESTATION_INVALID',
  'EVIDENCE_HASH_MISMATCH',
  'DELEGATION_PROVENANCE_INVALID',
  'DELEGATION_PROVENANCE_REQUIRED',
  'FINALIZATION_ISOLATION_FAILED',
  'FINALIZATION_FAILED',
  'PUBLICATION_POLICY_DENIED',
  'PUBLICATION_FAILED',
  'ABORTED',
  'UNKNOWN_FAILURE',
] as const;

export type RuntimeFailureCodeV4 = (typeof RUNTIME_FAILURE_CODES_V4)[number];

export interface RuntimeFailureV4 {
  code: RuntimeFailureCodeV4;
  message: string;
  retryable: boolean;
  evidence_hashes: readonly string[];
}
